Repository CSID-DGU/2025-1-SCS4031-JJangIJI-04, pull requests merged in 2025-06, with the labels that each got.

#121 [FE] 식당 추천 페이지를 개선하였다.
  frontend/public/images/basic-restaurant.svg
  frontend/src/assets/icons/bronze-medal.svg
  frontend/src/assets/icons/gold-medal.svg
  frontend/src/assets/icons/silver-medal.svg
  frontend/src/features/restaurant/api/restaurantApi.ts
  frontend/src/features/restaurant/api/useRecommendedRestaurants.ts
  frontend/src/features/restaurant/api/useRestaurantDetail.ts
  frontend/src/features/restaurant/hooks/useRestaurants.ts
  frontend/src/features/restaurant/mutations/useToggleBookmark.ts
  frontend/src/features/restaurant/types/restaurantDetail.ts
  frontend/src/features/restaurant/ui/IconTextRow.tsx
  frontend/src/features/restaurant/ui/RestaurantListItem.tsx
  frontend/src/features/restaurant/ui/crown/Crown.tsx
  frontend/src/pages/Restaurants/RestaurantDetailPage.tsx
  frontend/src/pages/Restaurants/RestaurantsPage.tsx
Labels: 💡 feature, 🔑 FE, ⚒️ refactor

#125 [BE] CI/CD 작업 속도를 줄인다.
  .github/workflows/backend-cd.yml
  .github/workflows/backend-ci.yml
Labels: 🔐 BE, ⚙️ chore

#127 [BE] DEV와 DEV-BE 병합한다.
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/domain/Category.java
Labels: 🔐 BE

#130 [BE] 북마크, 이모지 누른 피드 조회하는 API를 구현한다.
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/controller/ExpenseController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/repository/ExpenseRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/ExpenseService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/controller/RestaurantController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/repository/RestaurantRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/RecommendClient.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/RestaurantService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/dto/response/RecommendRestaurantResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/dto/response/RestaurantSimpleResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/user/controller/BookmarkController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/user/repository/BookmarkRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/user/service/BookmarkService.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/repository/ExpenseRepositoryTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/restaurant/service/RestaurantServiceTest.java
Labels: 🔐 BE, 💡 feature

#138 [BE] 추천 서버 데이터 요청시 식당 평점과 피드백 추가
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/exception/ExceptionCode.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/controller/RestaurantController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/domain/RecommendationFeedback.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/repository/RecommendationFeedbackRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/repository/RestaurantRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/RecommendClient.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/RestaurantService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/dto/reqeust/RecommendServerRestaurantsRequest.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/dto/reqeust/RecommendationFeedbackRequest.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/dto/response/RestaurantAverageRatingResponse.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/restaurant/repository/RestaurantRepositoryTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/restaurant/service/RestaurantServiceTest.java
Labels: 🔐 BE, 💡 feature

#139 [BE] 추천 로직 변경사항을 배포한다.
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/exception/ExceptionCode.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/controller/RestaurantController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/domain/RecommendationFeedback.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/repository/RecommendationFeedbackRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/repository/RestaurantRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/RecommendClient.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/RestaurantService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/dto/reqeust/RecommendServerRestaurantsRequest.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/dto/reqeust/RecommendationFeedbackRequest.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/dto/response/RestaurantAverageRatingResponse.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/restaurant/repository/RestaurantRepositoryTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/restaurant/service/RestaurantServiceTest.java
Labels: 🔐 BE

#140 [BE] 에러 수정하여 재배포한다.
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/auth/controller/AuthController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/RestaurantService.java
Labels: 🔐 BE, 💡 feature

#141 [BE] 추천 만족도4개 선택지로 변경한다.
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/domain/RecommendationFeedback.java
Labels: 🔐 BE, 💡 feature
