Repository CSID-DGU/2025-1-SCS4031-JJangIJI-04, pull requests merged in 2025-05, with the labels that each got.

#45 [FE] 회원가입 페이지를 구현하였다.
  frontend/public/icons/categories/asian-food.svg
  frontend/public/icons/categories/chinese-food.svg
  frontend/public/icons/categories/japanese-food.svg
  frontend/public/icons/categories/korean-food.svg
  frontend/public/icons/categories/korean-street-food.svg
  frontend/public/icons/categories/mexican-food.svg
  frontend/public/icons/categories/other-food.svg
  frontend/public/icons/categories/western-food.svg
  frontend/public/icons/close-outline.svg
  frontend/src/app/routes/PrivateRoute.tsx
  frontend/src/app/routes/index.tsx
  frontend/src/app/styles/global.ts
  frontend/src/features/auth/api/authApi.ts
  frontend/src/features/auth/mutations/useSignup.ts
  frontend/src/features/auth/store/useAuthStore.ts
  frontend/src/features/auth/types/auth.ts
  frontend/src/features/preferences/ui/CategorySelector.tsx
  frontend/src/pages/Landing/LandingPage.tsx
  frontend/src/pages/OAuthCallbackPage/OAuthCallbackPage.tsx
  frontend/src/pages/SignupPage/SignupPage.tsx
  frontend/src/shared/layouts/Layout.tsx
  frontend/src/shared/ui/Divider/FullWidthDivider.tsx
  frontend/src/shared/ui/InputField/InputField.tsx
  frontend/src/shared/ui/InputField/index.ts
Labels: 💡 feature, 🔑 FE

#46 [BE] 이모지 추가 / 삭제 API를 구현한다.
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/exception/ExceptionCode.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/controller/EmojiController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/controller/ExpenseController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/controller/ExpenseSavingGoalController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/ExpenseEmoji.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/repository/ExpenseEmojiRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/EmojiService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/ExpenseMapper.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/ExpenseSavingGoalService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/ExpenseService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/request/EmojiCreateRequest.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/request/EmojiDeleteRequest.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/request/ExpenseCreateRequest.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/request/ExpenseSavingGoalCreateRequest.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/response/DailyExpenseResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/response/EmojiCreateResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/response/ExpenseResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/response/ExpenseSavingGoalCreateResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/response/MonthlyExpenseResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/response/SavingGoalStatusResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/response/SimpleExpenseResponse.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/repository/ExpenseEmojiRepositoryTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/service/EmojiServiceTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/service/ExpenseSavingGoalTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/service/ExpenseServiceTest.java
Labels: 🔐 BE, 💡 feature

#52 [BE] 카카오 로그인 응답값을 변경한다.
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/auth/controller/AuthController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/auth/service/AuthService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/auth/service/dto/response/AuthResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/auth/service/dto/response/AuthTokenResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/auth/service/oauth/OauthClient.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/auth/service/oauth/OauthRequestProperties.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/EmojiService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/ExpenseMapper.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/ExpenseService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/user/domain/User.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/HankkimoaApplicationTests.java
Labels: 🔐 BE, 💡 feature

#54 [BE] cd 파일을 수정한다.
  .github/workflows/backend-cd.yml
Labels: 🔐 BE

#56 [FE] 목표 금액 입력 페이지를 구현하였다.
  .github/workflows/frontend-deploy.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/routes/PrivateRoute.tsx
  frontend/src/app/routes/index.tsx
  frontend/src/features/auth/api/authApi.ts
  frontend/src/features/auth/hooks/useCheckUserCompletion.ts
  frontend/src/features/auth/hooks/useKakaoLogin.ts
  frontend/src/features/auth/types/auth.ts
  frontend/src/features/auth/ui/KakaoLoginButton/KakaoLoginButton.tsx
  frontend/src/features/goals/api/requestAddSavingGoal.ts
  frontend/src/features/goals/mutations/useAddSavingGoal.ts
  frontend/src/lib/date/getCurrentWeek.ts
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/OAuthCallbackPage/OAuthCallbackPage.tsx
  frontend/src/pages/WeeklyGoalPage/WeeklyGoalPage.tsx
  frontend/src/shared/layouts/Layout.tsx
  frontend/src/shared/ui/InputField/InputField.tsx
  frontend/src/shared/ui/LoadingSpinner/LoadingSpinner.tsx
Labels: 💡 feature, 🔑 FE, ⚒️ refactor

#48 [FE] 식당 UI를 구현하였다.
  frontend/public/icons/restaurants/menu.svg
  frontend/public/icons/restaurants/place.svg
  frontend/public/icons/restaurants/price.svg
  frontend/public/icons/restaurants/time.svg
  frontend/public/images/sample1.png
  frontend/src/app/routes/index.tsx
  frontend/src/app/styles/global.ts
  frontend/src/features/restaurant/api/restaurantApi.ts
  frontend/src/features/restaurant/types/restaurant.ts
  frontend/src/features/restaurant/ui/IconTextRow.tsx
  frontend/src/features/restaurant/ui/RestaurantListItem.tsx
  frontend/src/features/restaurant/ui/bookmark/BookmarkButton.tsx
  frontend/src/features/restaurant/ui/bookmark/BookmarkIcon.tsx
  frontend/src/features/restaurant/ui/crown/Crown.tsx
  frontend/src/pages/Restaurants/RestaurantDetailPage.tsx
  frontend/src/pages/Restaurants/RestaurantsPage.tsx
Labels: 💡 feature, 🔑 FE

#60 [BE] 회원가입 API를 구현한다.
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/auth/config/AuthMvcConfig.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/auth/config/AuthRequiredPrincipal.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/auth/config/AuthRequiredPrincipalArgumentResolver.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/auth/controller/AuthController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/auth/controller/cookie/CookieResolver.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/auth/service/AuthService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/auth/service/dto/request/SignupRequest.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/auth/service/dto/response/SignupResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/exception/ExceptionCode.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/domain/Category.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/repository/CategoryRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/user/domain/Category.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/user/domain/User.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/user/domain/UserCategory.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/user/repository/UserCategoryRepository.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/auth/AuthServiceTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/config/IntegrationTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/config/RepositoryTest.java
Labels: 🔐 BE, 💡 feature

#63 [BE] 토큰 갱신 API를 구현한다.
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/auth/controller/AuthController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/auth/service/AuthService.java
Labels: 🔐 BE, 💡 feature

#64 [BE] 회원가입 기능에 대한 배포를 진행한다.
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/auth/config/AuthMvcConfig.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/auth/config/AuthRequiredPrincipal.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/auth/config/AuthRequiredPrincipalArgumentResolver.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/auth/controller/AuthController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/auth/controller/cookie/CookieResolver.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/auth/service/AuthService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/auth/service/dto/request/SignupRequest.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/auth/service/dto/response/SignupResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/exception/ExceptionCode.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/handler/GlobalExceptionHandler.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/domain/Category.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/repository/CategoryRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/user/domain/Category.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/user/domain/User.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/user/domain/UserCategory.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/user/repository/UserCategoryRepository.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/auth/AuthServiceTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/config/IntegrationTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/config/RepositoryTest.java
Labels: 🔐 BE

#65 [BE] yml 경로를 수정하여 배포한다.
  .github/workflows/backend-cd.yml
Labels: 🔐 BE, 🐛 bug

#66 [FE] 메인페이지 일부를 구현하고, 로그인 임시 테스트용 로직을 수정하였다.
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/routes/PrivateRoute.tsx
  frontend/src/app/routes/index.tsx
  frontend/src/app/styles/global.ts
  frontend/src/assets/icons/basic-icon.svg
  frontend/src/assets/icons/dangerous-icon.svg
  frontend/src/assets/icons/good-icon.svg
  frontend/src/assets/icons/home.svg
  frontend/src/assets/icons/insert-comment.svg
  frontend/src/assets/icons/navigate-after.svg
  frontend/src/assets/icons/navigate-before.svg
  frontend/src/assets/icons/normal-icon.svg
  frontend/src/assets/icons/person-outline.svg
  frontend/src/assets/icons/thumb-up.svg
  frontend/src/features/README.md
  frontend/src/features/calendar/types/expense.ts
  frontend/src/features/calendar/ui/ExpandableCalendar.tsx
  frontend/src/features/calendar/ui/FullCalendar.tsx
  frontend/src/features/calendar/ui/MiniCalendar.tsx
  frontend/src/features/spendingStatus/ui/GaugeChart.tsx
  frontend/src/lib/number/formatExpenseAmount.ts
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/OAuthCallbackPage/OAuthCallbackPage.tsx
  frontend/src/shared/layouts/Layout.tsx
  frontend/src/vite-env.d.ts
  frontend/src/widgets/BottomNavBar/BottomNavBar.tsx
  frontend/src/widgets/BottomNavBar/index.ts
  frontend/src/widgets/README.md
  frontend/vite.config.ts
Labels: 💡 feature, 🔑 FE

#70 [FE] 커뮤니티 UI를 구현하다
  frontend/public/icons/community/emojis/addEmoji.svg
  frontend/public/icons/community/emojis/burger.svg
  frontend/public/icons/community/emojis/chicken.svg
  frontend/public/icons/community/emojis/fingerHeart.svg
  frontend/public/icons/community/emojis/heartHands.svg
  frontend/public/icons/community/emojis/hundred.svg
  frontend/public/icons/community/emojis/loveEyes.svg
  frontend/public/icons/community/emojis/loveRibbon.svg
  frontend/public/icons/community/emojis/medal.svg
  frontend/public/icons/community/emojis/menu.png
  frontend/public/icons/community/emojis/menu.svg
  frontend/public/icons/community/emojis/moneyMouth.svg
  frontend/public/icons/community/emojis/partyFace.svg
  frontend/public/icons/community/emojis/partyPopper.svg
  frontend/public/icons/community/emojis/pizza.svg
  frontend/public/icons/community/emojis/pray.svg
  frontend/public/icons/community/emojis/question.svg
  frontend/public/icons/community/emojis/rice.svg
  frontend/public/icons/community/emojis/rose.svg
  frontend/public/icons/community/emojis/salad.svg
  frontend/public/icons/community/emojis/sandwitch.svg
  frontend/public/icons/community/emojis/smile.svg
  frontend/public/icons/community/emojis/store.svg
  frontend/public/icons/community/emojis/surprised.svg
  frontend/public/icons/community/emojis/thumbsUp.svg
  frontend/public/icons/community/emojis/tongue.svg
  frontend/public/icons/community/emojis/victory.svg
  frontend/public/icons/community/emojis/wallet.svg
  frontend/public/icons/community/user-avatar.svg
  frontend/src/app/routes/index.tsx
  frontend/src/app/styles/global.ts
  frontend/src/features/community/api/communityApi.ts
  frontend/src/features/community/constants/emojiMap.ts
  frontend/src/features/community/types/community.ts
  frontend/src/features/community/ui/BudgetGauge.tsx
  frontend/src/features/community/ui/Card.tsx
  frontend/src/features/community/ui/CommunityCard.tsx
  frontend/src/features/community/ui/EmojiAddButton.tsx
  frontend/src/features/community/ui/EmojiPopover.tsx
  frontend/src/features/community/ui/EmojiReactionPanel.tsx
  frontend/src/pages/Community/CommunityPage.tsx
Labels: 💡 feature, 🔑 FE

#69 [BE] 사용자 정보 조회 API 추가
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/auth/controller/cookie/CookieResolver.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/user/UserController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/user/repository/UserCategoryRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/user/repository/UserRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/user/service/UserService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/user/service/dto/CategoryResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/user/service/dto/UserMeResponse.java
Labels: 🔐 BE, 💡 feature

#74 [FE] 메인페이지 UI를 구현하였다.
  frontend/src/assets/icons/file.svg
  frontend/src/assets/icons/menu.svg
  frontend/src/assets/icons/store.svg
  frontend/src/assets/icons/wallet.svg
  frontend/src/features/calendar/ui/ExpandableCalendar.tsx
  frontend/src/features/calendar/ui/FullCalendar.tsx
  frontend/src/features/calendar/ui/MiniCalendar.tsx
  frontend/src/features/community/ui/EmojiReactionPanel.tsx
  frontend/src/features/spendingStatus/ui/DailyExpenseSection.tsx
  frontend/src/features/spendingStatus/ui/ExpenseCard.tsx
  frontend/src/features/spendingStatus/ui/GaugeChart.tsx
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/README.md
  frontend/src/shared/layouts/Layout.tsx
Labels: 💡 feature, 🔑 FE

#73 [BE] 지출 내역 조회시 이모지 가져오는 기능을 구현한다.
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/controller/ExpenseController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/controller/ExpenseSavingGoalController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/DailyExpenses.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/Expense.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/repository/ExpenseEmojiRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/repository/ExpenseRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/repository/ExpenseSavingGoalRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/ExpenseSavingGoalService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/ExpenseService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/response/EmojiResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/response/ExpenseResponse.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/domain/DailyExpensesTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/repository/ExpenseEmojiRepositoryTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/repository/ExpenseRepositoryTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/service/ExpenseSavingGoalTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/service/ExpenseServiceTest.java
Labels: 🔐 BE, 💡 feature, ⚒️ refactor

#78 [BE] 커뮤니티 글을 조회한다.
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/exception/ExceptionCode.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/controller/ExpenseController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/DailyExpenses.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/Expense.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/ExpenseSavingGoal.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/SavingGoalStatusMessage.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/repository/ExpenseEmojiRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/repository/ExpenseRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/repository/ExpenseSavingGoalRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/ExpenseService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/response/CommunityExpenseResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/response/DailyExpenseResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/response/EmojiResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/response/MonthlyExpenseResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/response/SimpleExpenseResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/response/TodayExpenses.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/repository/ExpenseEmojiRepositoryTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/repository/ExpenseRepositoryTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/repository/ExpenseSavingGoalRepositoryTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/service/ExpenseServiceTest.java
Labels: 🔐 BE, 💡 feature

#80 [BE] 가용 금액 조회 API를 구현한다.
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/ExpenseSavingGoalService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/response/RemainingBudgetResponse.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/service/ExpenseSavingGoalTest.java
Labels: 🔐 BE, 💡 feature

#68 [BE] 북마크 추가/제거/조회 API 추가
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/exception/ExceptionCode.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/user/controller/BookmarkController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/user/domain/Bookmark.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/user/repository/BookmarkRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/user/service/BookmarkService.java
Labels: 🔐 BE, 💡 feature

#81 [BE] DEV와 DEV-BE를 병합한다.
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/exception/ExceptionCode.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/controller/ExpenseController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/controller/ExpenseSavingGoalController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/DailyExpenses.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/Expense.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/ExpenseSavingGoal.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/SavingGoalStatusMessage.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/repository/ExpenseRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/repository/ExpenseSavingGoalRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/ExpenseSavingGoalService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/ExpenseService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/response/CommunityExpenseResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/response/DailyExpenseResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/response/EmojiResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/response/ExpenseResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/response/MonthlyExpenseResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/response/RemainingBudgetResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/response/SimpleExpenseResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/response/TodayExpenses.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/domain/DailyExpensesTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/repository/ExpenseEmojiRepositoryTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/repository/ExpenseRepositoryTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/repository/ExpenseSavingGoalRepositoryTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/service/ExpenseSavingGoalTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/service/ExpenseServiceTest.java
Labels: 🔐 BE

#83 [FE] 지출 기록 페이지를 구현하였다.
  frontend/src/app/routes/index.tsx
  frontend/src/assets/icons/circle-point.svg
  frontend/src/assets/icons/database.svg
  frontend/src/features/record/api/useGetRemainingBudget.ts
  frontend/src/features/record/mutations/useAddExpense.ts
  frontend/src/features/record/ui/StarRating.tsx
  frontend/src/pages/RecordPage/RecordPage.tsx
  frontend/src/shared/ui/Divider/FullWidthDivider.tsx
  frontend/src/shared/ui/InputField/InputField.tsx
Labels: 💡 feature, 🔑 FE

#87 [FE] 메인페이지 로직 구현 및 API 연동을 하였다.
  frontend/src/features/auth/hooks/useAuthInit.ts
  frontend/src/features/auth/store/useAuthStore.ts
  frontend/src/features/calendar/api/useWeeklyExpenseStatus.ts
  frontend/src/features/spendingStatus/api/useDailyExpenses.ts
  frontend/src/features/spendingStatus/ui/ExpenseCard.tsx
  frontend/src/pages/MainPage/MainPage.tsx
Labels: 💡 feature, 🔑 FE

#88 [BE] 식당 검색 API 기능을 구현한다.
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/controller/ExpenseSavingGoalController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/controller/RestaurantController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/domain/Address.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/domain/Restaurant.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/domain/RestaurantAddress.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/repository/RestaurantAddressRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/repository/RestaurantRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/RestaurantService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/dto/RestaurantSearchResponse.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/config/IntegrationTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/domain/DailyExpenseTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/domain/DailyExpensesTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/domain/ExpenseSavingGoalTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/domain/ExpenseTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/repository/ExpenseEmojiRepositoryTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/repository/ExpenseRepositoryTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/service/EmojiServiceTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/service/ExpenseServiceTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/restaurant/service/RestaurantServiceTest.java
Labels: 🔐 BE, 💡 feature

#92 [FE] 지출 기록 페이지 음식점 검색 드롭다운 인풋을 구현하였다.
  frontend/src/features/auth/hooks/useAuthInit.ts
  frontend/src/features/goals/api/useRemainingBudget.ts
  frontend/src/features/record/mutations/useAddExpense.ts
  frontend/src/features/record/ui/RestaurantSearchInput.tsx
  frontend/src/features/record/ui/StarRating.tsx
  frontend/src/features/restaurant/api/restaurantApi.ts
  frontend/src/features/restaurant/types/restaurant.ts
  frontend/src/hooks/useDebounce.ts
  frontend/src/pages/RecordPage/RecordPage.tsx
Labels: 💡 feature, 🔑 FE

#94 [BE] 지출 내역 추가 request 값 변경
  .github/workflows/backend-cd.yml
  .github/workflows/backend-ci.yml
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/ExpenseService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/request/ExpenseCreateRequest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/service/ExpenseServiceTest.java
Labels: 🔐 BE, 🐛 bug

#96 [FE] 메인 페이지의 로직을 수정하였다.
  frontend/src/features/goals/api/useRemainingBudgetByDate.ts
  frontend/src/pages/MainPage/MainPage.tsx
Labels: 💡 feature, 🔑 FE

#98 [BE] 오타 수정 및 타임존 설정을 추가한다.
  .github/workflows/backend-cd.yml
  .github/workflows/backend-ci.yml
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/Expense.java
Labels: 🔐 BE, 🐛 bug

#100 [FE] 커뮤니티 페이지를 백엔드와 연동하였다.
  frontend/src/features/community/api/communityApi.ts
  frontend/src/features/community/api/useAddEmoji.ts
  frontend/src/features/community/api/useCommunityPosts.ts
  frontend/src/features/community/api/useDeleteEmoji.ts
  frontend/src/features/community/constants/emojiMap.ts
  frontend/src/features/community/types/community.ts
  frontend/src/features/community/types/emoji.ts
  frontend/src/features/community/ui/Card.tsx
  frontend/src/features/community/ui/CommunityCard.tsx
  frontend/src/features/community/ui/EmojiAddButton.tsx
  frontend/src/features/community/ui/EmojiPopover.tsx
  frontend/src/features/community/ui/EmojiReactionPanel.tsx
  frontend/src/pages/Community/CommunityPage.tsx
  frontend/src/shared/hooks/useIntersectionObserver.ts
Labels: 💡 feature, 🔑 FE

#102 [BE] NotNull 조건을 추가한다.
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/controller/EmojiController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/Expense.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/ExpenseEmoji.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/ExpenseService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/request/EmojiCreateRequest.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/request/EmojiDeleteRequest.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/request/ExpenseCreateRequest.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/request/ExpenseSavingGoalCreateRequest.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/domain/Menu.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/domain/OpeningHours.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/domain/Restaurant.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/domain/RestaurantImage.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/dto/RestaurantCreateRequest.java
Labels: 🔐 BE, 💡 feature

#104 [FE] 마이페이지 UI를 구현하다
  frontend/public/icons/arrow-left.svg
  frontend/public/icons/arrow-right.svg
  frontend/public/icons/settings.svg
  frontend/src/app/routes/index.tsx
  frontend/src/features/community/hooks/useCommunity.ts
  frontend/src/features/myPage/ui/FullScreenPopup.tsx
  frontend/src/features/preferences/ui/CategorySelector.tsx
  frontend/src/features/restaurant/hooks/useRestaurants.ts
  frontend/src/pages/MyPage/MyPage.tsx
Labels: 💡 feature, 🔑 FE

#105 [BE] 중복된 식당 데이터 저장하지 않도록 수정한다.
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/domain/Restaurant.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/repository/RestaurantRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/RestaurantService.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/restaurant/service/RestaurantServiceTest.java
Labels: 🔐 BE, ⚒️ refactor

#110 [BE] 식당 조회 API를 구현한다.
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/controller/RestaurantController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/repository/MenuRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/repository/RestaurantImageRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/RestaurantService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/dto/reqeust/MenuRequest.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/dto/reqeust/OpeningHoursDetailRequest.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/dto/reqeust/OpeningHoursRequest.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/dto/reqeust/RestaurantCreateRequest.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/dto/response/MenuResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/dto/response/RecommendRestaurantResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/dto/response/RestaurantResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/service/dto/response/RestaurantSearchResponse.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/restaurant/service/RestaurantServiceTest.java
Labels: 🔐 BE, 💡 feature

#115 [FE] 마이페이지 유저 데이터를 받아올 수 있도록 수정하였다.
  frontend/public/icons/bookmarks.svg
  frontend/public/icons/insert-comment.svg
  frontend/src/app/routes/PrivateRoute.tsx
  frontend/src/features/auth/api/useUserInfo.ts
  frontend/src/features/myPage/api/useMonthlyExpenseTotal.ts
  frontend/src/features/myPage/ui/FullScreenPopup.tsx
  frontend/src/pages/MyPage/MyPage.tsx
Labels: 💡 feature, 🔑 FE

#114 [BE] 이모지 응답값 변경 및 이모지 삭제 API 요청값을 변경한다.
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/DailyExpenses.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/ExpenseEmojis.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/repository/ExpenseEmojiRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/EmojiService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/ExpenseService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/request/EmojiDeleteRequest.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/response/EmojiResponse.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/domain/ExpenseEmojisTest.java
Labels: 🔐 BE, ⚒️ refactor

#118 [FE] 커뮤니티 페이지를 리팩토링 하였다.
  frontend/src/app/routes/index.tsx
  frontend/src/features/community/api/communityApi.ts
  frontend/src/features/community/api/useToggleEmoji.ts
  frontend/src/features/community/hooks/useCommunity.ts
  frontend/src/features/community/types/community.ts
  frontend/src/features/community/types/emoji.ts
  frontend/src/features/community/ui/CommunityCard.tsx
  frontend/src/features/community/ui/EmojiReactionPanel.tsx
  frontend/src/features/spendingStatus/pages/GeneralExpensePage.tsx
  frontend/src/pages/Community/CommunityPage.tsx
  frontend/src/pages/GeneralExpensePageWrapper/GeneralExpensePageWrapper.tsx
Labels: 🔑 FE, ⚒️ refactor
