Repository CSID-DGU/2025-1-SCS4031-JJangIJI-04, pull requests merged in 2025-04, with the labels that each got.

#3 [BE] 프로젝트 초기 셋팅을 한다.
  backend/hankkimoa/.gitattributes
  backend/hankkimoa/.gitignore
  backend/hankkimoa/build.gradle
  backend/hankkimoa/gradle/wrapper/gradle-wrapper.jar
  backend/hankkimoa/gradle/wrapper/gradle-wrapper.properties
  backend/hankkimoa/gradlew
  backend/hankkimoa/gradlew.bat
  backend/hankkimoa/settings.gradle
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/HankkimoaApplication.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/BaseEntity.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/config/WebMvcConfig.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/exception/ExceptionCode.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/exception/ExceptionResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/exception/HankkiMoaException.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/handler/GlobalExceptionHandler.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/HankkimoaApplicationTests.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/common/HandlerTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/common/JpaAuditingTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/common/TestRepository.java
  backend/hankkimoa/src/test/java/resources/application-test.yml
Labels: 🔐 BE, ⚙️ chore

#4 [BE] 프로젝트 초기 셋팅을 한다.
  backend/hankkimoa/Dockerfile
  backend/hankkimoa/build.gradle
  backend/hankkimoa/src/test/java/resources/application-test.yml
Labels: 🔐 BE, ⚙️ chore

#7 [FE] 프로젝트 초기 세팅을 한다. (기본적인 라이브러리 포함)
  frontend/.gitignore
  frontend/README.md
  frontend/eslint.config.js
  frontend/index.html
  frontend/package.json
  frontend/public/vite.svg
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/assets/react.svg
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/vite-env.d.ts
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
Labels: 🔑 FE, ⚙️ chore

#11 [BE] 지출 생성 API를 구현한다.
  backend/hankkimoa/build.gradle
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/exception/ExceptionCode.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/handler/GlobalExceptionHandler.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/controller/ExpenseController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/Expense.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/ExpenseSavingGoal.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/repository/ExpenseRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/repository/ExpenseSavingGoalRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/ExpenseService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/ExpenseCreateRequest.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/domain/Restaurant.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/repository/RestaurantRepository.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/IntegrationTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/domain/ExpenseTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/service/ExpenseServiceTest.java
Labels: 🔐 BE, 💡 feature

#13 [BE] CI/CD를 구축한다
  .github/workflows/CD.yml
  .github/workflows/CI.yml
Labels: 🔐 BE, ⚙️ chore

#14 [BE] 지출 내역 삭제 API를 구현한다.
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/exception/ExceptionCode.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/controller/ExpenseController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/ExpenseService.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/service/ExpenseServiceTest.java
Labels: 🔐 BE, 💡 feature

#19 [BE] 프로젝트 CI/CD를 구축한다
  .github/workflows/backend-cd.yml
  .github/workflows/backend-ci.yml
Labels: 🔐 BE, ⚙️ chore

#20 [FE] CI/CD를 구축한다.
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  .github/workflows/frontend-deploy.yml
  backend/hankkimoa/.gitattributes
  backend/hankkimoa/.gitignore
  backend/hankkimoa/Dockerfile
  backend/hankkimoa/build.gradle
  backend/hankkimoa/gradle/wrapper/gradle-wrapper.jar
  backend/hankkimoa/gradle/wrapper/gradle-wrapper.properties
  backend/hankkimoa/gradlew
  backend/hankkimoa/gradlew.bat
  backend/hankkimoa/settings.gradle
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/HankkimoaApplication.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/BaseEntity.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/config/WebMvcConfig.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/exception/ExceptionCode.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/exception/ExceptionResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/exception/HankkiMoaException.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/handler/GlobalExceptionHandler.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/controller/ExpenseController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/Expense.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/ExpenseSavingGoal.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/repository/ExpenseRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/repository/ExpenseSavingGoalRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/ExpenseService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/ExpenseCreateRequest.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/domain/Restaurant.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/restaurant/repository/RestaurantRepository.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/HankkimoaApplicationTests.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/IntegrationTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/common/HandlerTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/common/JpaAuditingTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/common/TestRepository.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/domain/ExpenseTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/service/ExpenseServiceTest.java
  backend/hankkimoa/src/test/java/resources/application-test.yml
Labels: 🔑 FE, ⚙️ chore

#21 [FE] Prettier 및 ESLint 설정을 완료한다.
  frontend/eslint.config.js
  frontend/package.json
  frontend/prettier.config.js
Labels: 🔑 FE, ⚙️ chore

#25 [FE] 메인 페이지 초기 마크업 및 기본 프로젝트 세팅을 하였다.
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/icons/logo.png
  frontend/public/vite.svg
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/app/App.tsx
  frontend/src/app/routes/PrivateRoute.tsx
  frontend/src/app/routes/index.tsx
  frontend/src/app/styles/global.ts
  frontend/src/assets/react.svg
  frontend/src/entities/README.md
  frontend/src/features/README.md
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/pages/README.md
  frontend/src/shared/README.md
  frontend/src/shared/layouts/Layout.tsx
  frontend/src/widgets/README.md
  frontend/tsconfig.app.json
  frontend/vite.config.ts
Labels: 💡 feature, 🔑 FE, ⚙️ chore

#27 [FE] 랜딩페이지를 구현하였다.
  frontend/public/images/kakao-login-button.png
  frontend/src/app/App.tsx
  frontend/src/app/routes/index.tsx
  frontend/src/app/styles/global.ts
  frontend/src/features/auth/ui/KakaoLoginButton/KakaoLoginButton.tsx
  frontend/src/pages/Landing/LandingPage.tsx
Labels: 💡 feature, 🔑 FE

#29 [BE] 지출 내역 API 구현한다.
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/exception/ExceptionCode.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/controller/ExpenseController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/ExpenseByDate.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/ExpenseSavingGoal.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/ExpenseStatus.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/SavingGoalStatus.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/repository/ExpenseRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/ExpenseService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/DateExpenseResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/ExpenseResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/SavingGoalStatusResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/SimpleExpenseResponse.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/config/IntegrationTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/config/RepositoryTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/config/RepositoryTestConfig.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/domain/ExpenseByDateTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/domain/ExpenseSavingGoalTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/domain/SimpleExpenseResponseStatusTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/repository/ExpenseRepositoryTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/service/ExpenseServiceTest.java
  backend/hankkimoa/src/test/java/resources/application-test.yml
Labels: 🔐 BE, 💡 feature

#31 [BE] HTTPS 연결 및 설정정보 일부를 변경한다.
  .github/workflows/backend-cd.yml
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/config/WebMvcConfig.java
Labels: 🔐 BE, ⚙️ chore

#37 [BE] 도커 환경을 설정한다.
  .github/workflows/backend-nginx-cd.yml
  deploy/nginx/Dockerfile
  deploy/nginx/default.conf
  deploy/nginx/docker-compose.yml
Labels: 🔐 BE, ⚙️ chore

#35 [BE] 지출 한달 내역 조회 API를 구현한다.
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/exception/ExceptionCode.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/controller/ExpenseController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/DailyExpense.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/DailyExpenses.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/ExpenseSavingGoal.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/ExpenseStatus.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/repository/ExpenseRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/ExpenseService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/DailyExpenseResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/DateExpenseResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/MonthlyExpenseResponse.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/domain/DailyExpenseTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/domain/DailyExpensesTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/domain/ExpenseStatusTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/domain/SimpleExpenseResponseStatusTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/repository/ExpenseRepositoryTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/service/ExpenseServiceTest.java
Labels: 🔐 BE, 💡 feature

#40 [FE] 카카오 소셜 로그인을 구현하였다.
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/App.tsx
  frontend/src/app/providers/ReactQueryProvider.tsx
  frontend/src/app/routes/PrivateRoute.tsx
  frontend/src/app/routes/index.tsx
  frontend/src/features/auth/api/authApi.ts
  frontend/src/features/auth/api/requestRefreshToken.ts
  frontend/src/features/auth/hooks/useAuthInit.ts
  frontend/src/features/auth/hooks/useKakaoLogin.ts
  frontend/src/features/auth/store/useAuthStore.ts
  frontend/src/features/auth/types/auth.ts
  frontend/src/features/auth/ui/KakaoLoginButton/KakaoLoginButton.tsx
  frontend/src/lib/axios.ts
  frontend/src/pages/OAuthCallbackPage/OAuthCallbackPage.tsx
  frontend/src/shared/layouts/Layout.tsx
Labels: 💡 feature, 🔑 FE

#44 [BE] 지출 목표 금액 추가 API를 구현한다.
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/common/exception/ExceptionCode.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/controller/ExpenseSavingGoalController.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/domain/ExpenseSavingGoal.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/repository/ExpenseSavingGoalRepository.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/ExpenseSavingGoalService.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/ExpenseSavingGoalCreateRequest.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/expense/service/dto/ExpenseSavingGoalCreateResponse.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/user/domain/User.java
  backend/hankkimoa/src/main/java/com/jjangiji/hankkimoa/user/repository/UserRepository.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/domain/DailyExpenseTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/domain/DailyExpensesTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/domain/ExpenseSavingGoalTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/domain/ExpenseTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/repository/ExpenseRepositoryTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/repository/ExpenseSavingGoalRepositoryTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/service/ExpenseSavingGoalTest.java
  backend/hankkimoa/src/test/java/com/jjangiji/hankkimoa/expense/service/ExpenseServiceTest.java
Labels: 🔐 BE, 💡 feature
